<a href="https://colab.research.google.com/github/sathvik044/ML-ASS4-Q3/blob/main/ML_ASS4_Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/iris.csv')
df.head()


from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

x=df[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']]
y=df['Species']

# Split dataset into training set and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1) # 70% training and 30% test


clf = DecisionTreeClassifier(criterion='entropy')


clf = clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


from sklearn.tree import export_graphviz
import graphviz

dot_data=export_graphviz(clf,out_file=None)
graph=graphviz.Source(dot_data)

dot_data=export_graphviz(clf,out_file=None,feature_names=x.columns,filled=True,rounded=True,special_characters=True)
graph=graphviz.Source(dot_data)
graph

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


Accuracy: 0.9555555555555556
[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
